Use Docker for our build env
I think this will be a benefit overall, it gives us a reproducible build
environment that can be used in or outside of GitHub Actions.

Also, it will let us build in versions of Ubuntu/Debian other than what
GitHub Actions supports for runners, and possibly even other
architectures with Qemu.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -22,21 +22,34 @@ jobs:
       matrix:
         ubuntu_version: ["22.04", "24.04", "24.10"]
     runs-on: ubuntu-latest
-    container:
-      image: ubuntu:${{ matrix.ubuntu_version }}
     steps:
+        # See the docs: https://github.com/docker/build-push-action
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+
+        # This action checks out the source as part of the action and can therefore
+        # go before the checkout step.
+      - name: Build Docker Image
+        uses: docker/build-push-action@v6
+        with:
+          tags: ghostty-ubuntu:${{ matrix.ubuntu_version }}
+          build-args: |
+            UBUNTU_VERSION=${{ matrix.ubuntu_version }}
+          push: false
+          load: true
+          cache-from: type=gha
+          cache-to: type=gha,mode=max
+
       - name: Checkout ghostty-ubuntu
         uses: actions/checkout@v4
 
-      - name: Setup Build Env
-        run: ./setup-env.sh
-
       - name: Build Ghostty
-        run: ./build-ghostty.sh
+        run: docker run --rm -v$PWD:/workspace -w /workspace ghostty-ubuntu:${{ matrix.ubuntu_version }} /bin/bash build-ghostty.sh
 
       - name: Lint .deb Package
-        run: lintian ghostty_*.deb || true # Lintian shouldn't fail our build yet
-      
+        # Lintian shouldn't fail our build yet
+        run: docker run --rm -v$PWD:/workspace -w /workspace ghostty-ubuntu:${{ matrix.ubuntu_version }} lintian ghostty_*.deb || true 
+        
       - name: Upload Artifact
         uses: actions/upload-artifact@v4
         with:
